### ISSUE TITLE
Port unittests.mock package

### ISSUE THREAD

**Issue by naftaliharris** [naftaliharris/python2.8#11]

**Comment by naftaliharris** [comment]
Hmm, actually there is a private backport at Lib/test/_mock_backport.py...

**Comment by naftaliharris** [comment]
...but it doesn't work very well since it's still missing inspect.signature:

```python
>>> import test._mock_backport as mock
>>> class Foo(object): pass
...
>>> mock.MagicMock(Foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/naftali/repos/cpython/Lib/test/_mock_backport.py", line 1789, in __init__
    _safe_super(MagicMixin, self).__init__(*args, **kw)
  File "/Users/naftali/repos/cpython/Lib/test/_mock_backport.py", line 895, in __init__
    _spec_state, _new_name, _new_parent, **kwargs
  File "/Users/naftali/repos/cpython/Lib/test/_mock_backport.py", line 400, in __init__
    self._mock_add_spec(spec, spec_set, _spec_as_instance, _eat_self)
  File "/Users/naftali/repos/cpython/Lib/test/_mock_backport.py", line 457, in _mock_add_spec
    _spec_as_instance, _eat_self)
  File "/Users/naftali/repos/cpython/Lib/test/_mock_backport.py", line 100, in _get_signature_object
    return func, inspect.signature(sig_func)
AttributeError: 'module' object has no attribute 'signature'
>>>
```

**Comment by naftaliharris** [comment]
Diffing test._mock_backport and the unittest.mock in 3.5.2 shows that the 2.7 mock looks pretty good. Major substantial differences is a "visited" argument in reset_mock to prevent cycles, looks like a bugfix.

**Comment by naftaliharris** [comment]
Needs #14

**Comment by adamchainz** [comment]
Unnecessary as this exists: https://pypi.python.org/pypi/backports.unittest_mock/1.0
